### ISSUE TITLE
Website design, styling

### ISSUE THREAD

**Issue by jfelici4** [CS4370-Food-Truck/FoodTruckApp#27]
Make the maps website a little prettier. Adding borders, styles, user-friendliness.

**Comment by jfelici4** [comment]
#23 closed, should be safe to make changes with table

**Comment by jfelici4** [comment]
#46 adds a background image to the front page, though at the time of writing it makes the table view a little harder to read on some window sizes.

**Comment by ArturoVal** [comment]
#46 Resolves
