### ISSUE TITLE
Presentation Ideas

### ISSUE THREAD

**Issue by jfelici4** [CS4370-Food-Truck/FoodTruckApp#63]
What would you like to present to the class about our project?

**Comment by mrayne483** [comment]
Login/logout feature.

**Comment by ArturoVal** [comment]
Mobile view.

**Comment by karent2222** [comment]
The style changes on the website.

**Comment by jfelici4** [comment]
@karent2222 is beginning the presentation on google slides

**Comment by jfelici4** [comment]
Monday we are presenting the application part of the program (just for practice)

**Comment by jfelici4** [comment]
Practice presentation complete
